# Site settings
title: AI4Life Institute
name: AI4Life Institute
description: Empowering Innovation Through AI
url: https://ai4lifeinstitute.com
baseurl: ""

# Social media and contact
footer-links:
  email: info@ai4lifeinstitute.com
  facebook: ai4lifeinstitute
  github: AI4Life-Institute
  linkedin: company/ai4life-institute
  twitter: ai4life_inst

# Build settings
markdown: kramdown
encoding: utf-8

# Sass settings
sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - vendor
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
  - node_modules
  - package.json
  - package-lock.json
